reorganize apply and general cleaning

diff --git a/.github/workflows/run-checks.yaml b/.github/workflows/run-checks.yaml
--- a/.github/workflows/run-checks.yaml
+++ b/.github/workflows/run-checks.yaml
@@ -157,212 +157,256 @@ jobs:
       apply_comment_id: ${{ steps.apply-comment.outputs.comment-id }}
       additional_info: ${{ steps.link.outputs.additional }}
 
-  # lint:
+  # build_test:
+  #   # needs: [download_patches, create-issue, apply]
   #   needs: [download_patches, create-issue]
-  #   uses: ./.github/workflows/lint.yaml
-  #   permissions:
-  #     issues: write
-  #   with:
-  #     patch_name: ${{ inputs.patch_name }}
-  #     issue_num: ${{ needs.create-issue.outputs.issue_num }}
-  #     lint_comment_id: ${{ needs.create-issue.outputs.lint_comment_id }}
-  #     additional_info: ${{ needs.create-issue.outputs.additional_info }}
-  #     baseline_hash: ${{ inputs.baseline_hash }}
-  #   secrets: inherit
-
-  # apply:
-  #   needs: [download_patches, create-issue]
-  #   runs-on: ubuntu-22.04
-  #   environment: production
-  #   defaults:
-  #     run:
-  #       working-directory: riscv-gnu-toolchain
-  #   steps:
-  #     - uses: actions/checkout@v3
-
-  #     - name: Setup env
-  #       uses: ./.github/actions/common/setup-env
-  #       with:
-  #         free_up_space: false
-
-  #     - name: Restore submodules from cache
-  #       uses: actions/download-artifact@v3
-  #       with:
-  #         name: glibc-sources-${{ inputs.baseline_hash }}
-  #         path: ./riscv-gnu-toolchain
-
-  #     - name: Restore submodules
-  #       run: |
-  #         rm -rf .git binutils dejagnu gcc gdb glibc newlib qemu
-  #         unzip cache.zip
-  #         rm -rf cache.zip
-
-  #     - name: Download patches artifact
-  #       uses: actions/download-artifact@v3
-  #       with:
-  #         name: ${{ inputs.patch_name }}-downloaded-patches
-  #         path: ./riscv-gnu-toolchain
-
-  #     - name: Extract patches
-  #       run: |
-  #         unzip ${{ inputs.patch_name }}-downloaded-patches.zip
-
-  #     - name: Checkout glibc hash
-  #       run: |
-  #         cd glibc
-  #         git fetch
-  #         git checkout ${{ inputs.baseline_hash }}
-
-  #     - name: Apply patches to baseline
-  #       id: apply-baseline
-  #       run: |
-  #         cd glibc
-  #         git config user.name "GitHub Actions Bot"
-  #         git config user.email "<>"
-  #         git am ../patches/*.patch --whitespace=fix -q --3way --empty=drop &> out_base || true
-  #         cat out_base
-  #         if [[ $(cat out_base | wc -l) != 0 ]]; then
-  #           git am --show-current-patch=diff
-  #           echo "Failed to apply patch cleanly to baseline hash"
-  #           echo "\`\`\`" >> out_base
-  #           git am --show-current-patch=diff &>> out_base
-  #           echo "\`\`\`" >> out_base
-  #           git am --abort
-  #           echo "apply_baseline=false" >> $GITHUB_OUTPUT
-  #         else
-  #           echo "apply_baseline=true" >> $GITHUB_OUTPUT
-  #         fi
-  #       continue-on-error: true
-
-  #     - name: Apply patches to tip of tree
-  #       id: apply-tip-of-tree
-  #       run: |
-  #         cd glibc
-  #         git reset --hard ${{ inputs.tot_hash }}
-  #         git am ../patches/*.patch --whitespace=fix -q --3way --empty=drop &> out_tot || true
-  #         cat out_tot
-  #         if [[ $(cat out_tot | wc -l) != 0 ]]; then
-  #           git am --show-current-patch=diff
-  #           echo "Failed to apply patch cleanly to tip of tree"
-  #           git am --show-current-patch=diff &>> out_tot
-  #           git am --abort
-  #           echo "apply_tot=false" >> $GITHUB_OUTPUT
-  #         else
-  #           echo "apply_tot=true" >> $GITHUB_OUTPUT
-  #         fi
-  #       continue-on-error: true
-
-  #     - name: Check build only
-  #       id: build-only
-  #       if: ${{ steps.apply-baseline.outputs.apply_baseline == 'false' && steps.apply-tip-of-tree.outputs.apply_tot == 'true' }}
-  #       run: |
-  #         echo "build_only=true" >> $GITHUB_OUTPUT
-
-  #     - name: Check early exit
-  #       id: early-exit
-  #       if: ${{ steps.apply-baseline.outputs.apply_baseline == 'false' && steps.apply-tip-of-tree.outputs.apply_tot == 'false' }}
-  #       run: |
-  #         echo "early_exit=true" >> $GITHUB_OUTPUT
-
-  #     - name: Add Build-Only Label to issue
-  #       if: ${{ steps.build-only.outputs.build_only == 'true' }}
-  #       uses: actions/github-script@v6
-  #       with:
-  #         script: |
-  #           github.rest.issues.addLabels({
-  #             issue_number: ${{ needs.create-issue.outputs.issue_num }},
-  #             owner: context.repo.owner,
-  #             repo: context.repo.repo,
-  #             labels: ['build-only']
-  #           })
-
-  #     - name: Build apply report
-  #       run: |
-  #         python scripts/generate_apply_report.py -patch ${{ inputs.patch_name }} -bhash ${{ inputs.baseline_hash }} -thash ${{ inputs.tot_hash }} -bstatus ${{ steps.apply-baseline.outputs.apply_baseline }} -tstatus ${{ steps.apply-tip-of-tree.outputs.apply_tot }} -o comment.md
-  #         head -c 65000 comment.md > trimmed_comment.md
-  #         if [ $(cat trimmed_comment.md | wc -l) -ne $(cat comment.md | wc -l) ]; then printf "\n\`\`\`\nComment text has been trimmed. Please check logs for the untrimmed comment." >> trimmed_comment.md; fi
-  #         printf "\n[Additional information](${{ needs.create-issue.outputs.additional_info }})\n" >> trimmed_comment.md
-
-  #     - name: Update apply report comment
-  #       uses: peter-evans/create-or-update-comment@v3
-  #       id: apply-comment
-  #       env:
-  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-  #       with:
-  #         comment-id: ${{ needs.create-issue.outputs.apply_comment_id }}
-  #         body-path: riscv-gnu-toolchain/trimmed_comment.md
-  #         edit-mode: replace
-
-  #     - name: Report patch failed to apply to tip of tree
-  #       if: ${{ steps.apply-baseline.outputs.apply_baseline == 'true' && steps.apply-tip-of-tree.outputs.apply_tot == 'false' }}
-  #       run: |
-  #         python scripts/post_check_to_patchworks.py -event ${{ github.event_name }} -repo ewlu/riscv-glibc-ci -pid $(tail -n 1 patches/${{ inputs.patch_name }}) -desc 'Patch failed to apply to tip of tree.' -iid '${{ needs.create-issue.outputs.issue_num }}#issuecomment-${{ needs.create-issue.outputs.apply_comment_id }}' -state 'warning' -context 'apply-patch' -token "PLACEHOLDER"
-  #       continue-on-error: true
-
-  #     - name: Report patch applied to tip of tree successfully
-  #       if: ${{ steps.apply-tip-of-tree.outputs.apply_tot == 'true' }}
-  #       run: |
-  #         python scripts/post_check_to_patchworks.py -event ${{ github.event_name }} -repo ewlu/riscv-glibc-ci -pid $(tail -n 1 patches/${{ inputs.patch_name }}) -desc 'Patch applied' -iid '${{ needs.create-issue.outputs.issue_num }}#issuecomment-${{ needs.create-issue.outputs.apply_comment_id }}' -state 'success' -context 'apply-patch' -token "PLACEHOLDER"
-  #       continue-on-error: true
-
-  #     - name: Report patch failed to apply anywhere
-  #       if: ${{ steps.apply-baseline.outputs.apply_baseline == 'false' && steps.apply-tip-of-tree.outputs.apply_tot == 'false' }}
-  #       run: |
-  #         python scripts/post_check_to_patchworks.py -event ${{ github.event_name }} -repo ewlu/riscv-glibc-ci -pid $(tail -n 1 patches/${{ inputs.patch_name }}) -desc 'Patch failed to apply' -iid '${{ needs.create-issue.outputs.issue_num }}#issuecomment-${{ needs.create-issue.outputs.apply_comment_id }}' -state 'fail' -context 'apply-patch' -token "PLACEHOLDER"
-  #       continue-on-error: true
-
-  #     - name: Add apply-failure label if patch failed to apply anywhere
-  #       if: ${{ steps.apply-baseline.outputs.apply_baseline == 'false' && steps.apply-tip-of-tree.outputs.apply_tot == 'false' }}
-  #       uses: actions/github-script@v6
-  #       with:
-  #         script: |
-  #           github.rest.issues.addLabels({
-  #             issue_number: ${{ needs.create-issue.outputs.issue_num }},
-  #             owner: context.repo.owner,
-  #             repo: context.repo.repo,
-  #             labels: ['apply-failure']
-  #           })
-
-  #     - name: Output the hash after the patch has been applied
-  #       id: new-glibc-hash
-  #       if: ${{ steps.apply-baseline.outputs.apply_baseline == 'true' || steps.apply-tip-of-tree.outputs.apply_tot == 'true' }}
-  #       run: |
-  #         cd glibc
-  #         git reset --hard ${{ inputs.tot_hash }}
-  #         if [ "${{ steps.apply-baseline.outputs.apply_baseline }}" == "true" ]; then
-  #           git checkout ${{ inputs.baseline_hash }}
-  #         fi
-  #         git am ../patches/*.patch --whitespace=fix --3way --empty=drop
-  #         export PATCH_APPLIED_GCCHASH=$(git rev-parse HEAD)
-  #         echo $PATCH_APPLIED_GCCHASH
-  #         echo "patch_applied_glibchash=$PATCH_APPLIED_GCCHASH" >> $GITHUB_OUTPUT
-
-  #   outputs:
-  #     early_exit: ${{ steps.early-exit.outputs.early_exit }}
-  #     build_only: ${{ steps.build-only.outputs.build_only }}
-  #     patch_applied_glibchash: ${{ steps.new-glibc-hash.outputs.patch_applied_glibchash }}
-
-  # build_many_glibcs:
-  #   needs: [download_patches, create-issue, apply]
   #   if: ${{ needs.apply.outputs.early_exit != 'true' }}
-  #   uses: ./.github/workflows/build-glibcs.yaml
+  #   uses: ./.github/workflows/build-target.yaml
   #   with:
   #     patch_name: ${{ inputs.patch_name }}
   #     baseline_hash: ${{ inputs.baseline_hash }}
   #     build_only: ${{ needs.apply.outputs.build_only }}
-  #     patch_applied_glibchash: ${{ needs.apply.outputs.patch_applied_glibchash }}
-  #     tot_hash: ${{ inputs.tot_hash }}
-
-  build_test:
-    # needs: [download_patches, create-issue, apply]
+  #     issue_num: ${{ needs.create-issue.outputs.issue_num }}
+  #     apply_comment_id: ${{ needs.create-issue.outputs.apply_comment_id }}
+  #     additional_info: ${{ needs.create-issue.outputs.additional_info }}
+  #   secrets: inherit
+  
+  apply:
     needs: [download_patches, create-issue]
+    runs-on: ubuntu-22.04
+    environment: production
+    defaults:
+      run:
+        working-directory: ./glibc
+    steps:
+      - uses: actions/checkout@v3
+
+      - name: Setup env
+        uses: ./.github/actions/common/setup-env
+        with:
+          free_up_space: false
+
+      - name: Bump pyopenssl and crypto
+        run: |
+          sudo apt remove python3-pip
+          wget https://bootstrap.pypa.io/get-pip.py
+          sudo python3 get-pip.py
+          pip install -U pyopenssl cryptography
+          pip install pygithub==1.59.1 requests
+
+      - name: Download patches artifact
+        uses: actions/download-artifact@v3
+        with:
+          name: ${{ inputs.patch_name }}-downloaded-patches
+          path: ./glibc
+
+      - name: Extract patches
+        run: |
+          unzip ${{ inputs.patch_name }}-downloaded-patches.zip
+
+      - name: Apply patches to baseline
+        id: apply-baseline
+        run: |
+          git pull
+          git checkout ${{ inputs.baseline_hash }}
+          git am ./patches/*.patch --whitespace=fix -q --3way --empty=drop &> out || true
+          cat out_tot
+          if [[ $(cat out | wc -l) != 0 ]]; then
+            git am --show-current-patch=diff
+            echo "Failed to apply patch cleanly to tip of tree"
+            git am --show-current-patch=diff &>> out
+            git am --abort
+            echo "apply_baseline=false" >> $GITHUB_OUTPUT
+          else
+            echo "apply_baseline=true" >> $GITHUB_OUTPUT
+          fi
+        continue-on-error: true
+
+      - name: Check patch applied
+        id: early-exit
+        run: |
+          if [[ $(cat ./out | wc -l) != 0 ]];
+          then 
+            python scripts/generate_apply_report.py -patch ${{ inputs.patch_name }} -bhash ${{ inputs.baseline_hash }} -bstatus "false" -o comment.md
+            echo "early_exit=true" >> $GITHUB_OUTPUT
+          else
+            python scripts/generate_apply_report.py -patch ${{ inputs.patch_name }} -bhash ${{ inputs.baseline_hash }} -bstatus "true" -o comment.md
+            echo "early_exit=false" >> $GITHUB_OUTPUT
+          fi
+          head -c 65000 comment.md > trimmed_comment.md
+          if [ $(cat trimmed_comment.md | wc -l) -ne $(cat comment.md | wc -l) ]; then printf "\n\`\`\`\nComment text has been trimmed. Please check logs for the untrimmed comment." >> trimmed_comment.md; fi
+          printf "\n[Additional information](${{ inputs.additional_info }})\n" >> trimmed_comment.md
+
+      - name: Update apply report comment
+        uses: peter-evans/create-or-update-comment@v3
+        id: apply-comment
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        with:
+          comment-id: ${{ needs.create-issue.outputs.apply_comment_id }}
+          body-path: glibc/trimmed_comment.md
+          edit-mode: replace
+
+      - name: Add apply-failure label if patch failed to apply anywhere
+        if: ${{ steps.apply-baseline.outputs.apply_baseline == 'false' }}
+        uses: actions/github-script@v6
+        with:
+          script: |
+            github.rest.issues.addLabels({
+              issue_number: ${{ needs.create-issue.outputs.issue_num }},
+              owner: context.repo.owner,
+              repo: context.repo.repo,
+              labels: ['apply-failure']
+            })
+
+      - name: Output the hash after the patch has been applied
+        id: new-glibc-hash
+        if: ${{ steps.apply-baseline.outputs.apply_baseline == 'true' }}
+        run: |
+          git checkout ${{ inputs.baseline_hash }}
+          git am ../patches/*.patch --whitespace=fix --3way --empty=drop
+          export PATCH_APPLIED_GLIBCHASH=$(git rev-parse HEAD)
+          echo $PATCH_APPLIED_GLIBCHASH
+          echo "patch_applied_glibchash=$PATCH_APPLIED_GLIBCHASH" >> $GITHUB_OUTPUT
+
+    outputs:
+      early_exit: ${{ steps.early-exit.outputs.early_exit }}
+      patch_applied_glibchash: ${{ steps.new-glibc-hash.outputs.patch_applied_glibchash }}
+
+
+  initialize-comments:
+    runs-on: ubuntu-22.04
+    needs: [download_patches, create-issue, apply]
     if: ${{ needs.apply.outputs.early_exit != 'true' }}
-    uses: ./.github/workflows/build-target.yaml
+    defaults:
+      run:
+        working-directory: ./
+    steps:
+      - uses: actions/checkout@v3
+
+      - name: Setup env
+        uses: ./.github/actions/common/setup-env
+        with:
+          free_up_space: false
+
+      - name: Download patches artifact
+        uses: actions/download-artifact@v3
+        with:
+          name: ${{ inputs.patch_name }}-downloaded-patches
+          path: ./
+
+      - name: Extract patches
+        run: |
+          unzip ${{ inputs.patch_name }}-downloaded-patches.zip
+
+      - name: Create build pending comment
+        run: |
+          echo "## Build Many Glibcs Status" > build_pending_comment.md
+          printf "\n[Additional information](${{ needs.create-issue.outputs.additional_info }})\n" >> build_pending_comment.md
+
+      - name: Create build report comment
+        uses: peter-evans/create-or-update-comment@v3
+        id: build-comment
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        with:
+          issue-number: ${{ needs.create-issue.outputs.issue_num }}
+          body-path: ./build_pending_comment.md
+          edit-mode: replace
+
+      - name: Create build pending comment
+        run: |
+          echo "## Testing Glibcs Status" > test_pending_comment.md
+          printf "\n[Additional information](${{ needs.create-issue.outputs.additional_info }})\n" >> test_pending_comment.md
+
+      - name: Create build report comment
+        uses: peter-evans/create-or-update-comment@v3
+        id: test-comment
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        with:
+          issue-number: ${{ needs.create-issue.outputs.issue_num }}
+          body-path: ./test_pending_comment.md
+          edit-mode: replace
+
+    outputs:
+      build_glibc_comment_id: ${{ steps.build-comment.outputs.comment-id }}
+      test_glibc_comment_id: ${{ steps.test-comment.outputs.comment-id }}
+
+  # build-many-glibcs: 
+  #   needs: [initialize-comments]
+  #   uses: ./.github/workflows/build-glibcs.yaml
+  #   with:
+  #     patch_name: ${{ inputs.patch_name }}
+  #     baseline_hash: ${{ inputs.baseline_hash }}
+  #     patch_applied_glibchash: ${{ inputs.patch_applied_glibchash }}
+  #     issue_num: ${{ needs.create-issue.outputs.issue_num }}
+  #     build_comment_id: ${{ needs.initialize-comments.outputs.build_glibc_comment_id }}
+  #     run_on_self_hosted: false
+  #     tot_hash: ${{ inputs.tot_hash }}
+  #     additional_info: ${{ needs.create-issue.outputs.additional_info }}
+  #   secrets: inherit
+
+
+  test-glibc-linux-baseline:
+    # needs: [initialize-comments,make-rootfs-baseline]
+    needs: [download_patches, create-issue, initialize-comments]
+    uses: ./.github/workflows/test-regression.yaml
+    strategy:
+      fail-fast: false
+      matrix:
+        target:
+          [
+            # rv32gc-ilp32d,
+            rv64gc-lp64d,
+          ]
+    with:
+      patch_name: 
+      glibchash: ${{ inputs.baseline_hash }}
+      target: ${{ matrix.target }}
+      issue_num: ${{ needs.create-issue.outputs.issue_num }}
+      test_comment_id: ${{ needs.initialize-comments.outputs.test_comment_id }}
+      additional_info: ${{ needs.create-issue.outputs.additional_info }}
+      target_type: 'baseline'
+    secrets: inherit
+
+  test-glibc-linux-applied:
+    needs: [download_patches, create-issue, initialize-comments, apply]
+    # needs: [initialize-comments]
+    uses: ./.github/workflows/test-regression.yaml
+    strategy:
+      fail-fast: false
+      matrix:
+        target:
+          [
+            # rv32gc-ilp32d,
+            rv64gc-lp64d,
+          ]
     with:
       patch_name: ${{ inputs.patch_name }}
-      baseline_hash: ${{ inputs.baseline_hash }}
-      build_only: ${{ needs.apply.outputs.build_only }}
+      glibchash: ${{ needs.apply.outputs.patch_applied_glibchash }}
+      target: ${{ matrix.target }}
       issue_num: ${{ needs.create-issue.outputs.issue_num }}
-      apply_comment_id: ${{ needs.create-issue.outputs.apply_comment_id }}
+      test_comment_id: ${{ needs.initialize-comments.outputs.test_comment_id }}
       additional_info: ${{ needs.create-issue.outputs.additional_info }}
+      target_type: 'applied'
     secrets: inherit
+
+
+  # summarize:
+  #   if: "!cancelled()" # Generate github issues even when some (or all) targets fail to build
+  #   needs: [apply,initialize-comments,test-glibc-linux-applied,test-glibc-linux-baseline]
+  #   permissions:
+  #     issues: write
+  #   uses: ./.github/workflows/generate-precommit-summary.yaml
+  #   with:
+  #     patch_name: ${{ inputs.patch_name }}
+  #     baseline_hash: ${{ inputs.baseline_hash }}
+  #     patch_applied_glibchash: ${{ inputs.patch_applied_glibchash }}
+  #     build_only: ${{ inputs.build_only }}
+  #     tot_hash: ${{ inputs.tot_hash }}
+  #     issue_num: ${{ needs.create-issue.outputs.issue_num }}
+  #     build_comment_id: ${{ needs.initialize-comments.outputs.build_comment_id }}
+  #     test_comment_id: ${{ needs.initialize-comments.outputs.test_comment_id }}
+  #     additional_info: ${{ needs.create-issue.outputs.additional_info }}
+  #   secrets: inherit
